export { authenticationRouter } from "./authentication.router"
export { personalInfoQuestionRouter } from "./personal-info-question.router"
export { updatePasswordRoutes } from "./update-password.router"
export { userRoutes } from "./user.router"
export { validateCodeRouter } from "./validate-code.router"
